spring.application.name=SumativaCloudConsumidor
server.port=8081

# Configuracion para logs de AWS
logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG

# Configuracion S3
aws.s3.bucket=${S3_BUCKET_NAME}

# RabbitMQ
spring.rabbitmq.host=rabbitmq1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# H2
spring.datasource.url=jdbc:h2:file:/app/data/guiasdb;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always